name: thundergallery
description: "Photo Organizer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  permission_handler: ^12.0.0+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  meta: ^1.10.0
  photo_manager: 3.6.4
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  flutter_riverpod: ^2.4.9
  go_router: ^15.1.2
  intl: ^0.18.1
  file_picker: ^6.1.2
  path_provider: ^2.1.1
  cross_file: ^0.3.3

#  file_picker_windows: ^5.3.3
#  file_picker_macos: ^5.3.3
#  file_picker_linux: ^5.3.3

dependency_overrides:
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0  # Using flutter_lints instead of lints for better Flutter compatibility

flutter:
  uses-material-design: true
